# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 886624dc65368bdc3c52b0ca6ad7bdfc1107aeab7e83a079b38a508c5ca0c95c29379dfadce313f6fa130c6d90a11e6b4ff969056626db70b6ad3303c5c2eca5

test:
  secret_key_base: cb1e689749682930bee5e31c92015c616bb85295f199f27d04f80cf1f1659079e5d799fea10bb625b8e1d9448d578a5825f31ddc6a4d3e37f179feb905773551

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
